apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: api-qa-finance-deployment
spec:
  selector:
    matchLabels:
      app: api-qa-finance
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      name: api-qa-finance
      labels:
        app: api-qa-finance
    spec:
      containers:
        - name: api-qa-finance
          image: multiservicecr.azurecr.io/api-qa-finance:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: "ASPNETCORE_ENVIRONMENT"
              value: "qa"
      imagePullSecrets:
        - name: acr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: api-qa-finance-service
spec:
  type: NodePort
  selector:
    app: api-qa-finance
  ports:
    - name: api-qa-finance-port
      port: 80
      protocol: TCP
